// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe74ZYUkUYPuWK4YOsAP2NBR-4RaJ7zRo',
    appId: '1:84936949380:web:6d768e714891937fcc4cd1',
    messagingSenderId: '84936949380',
    projectId: 'memora-5db6f',
    authDomain: 'memora-5db6f.firebaseapp.com',
    storageBucket: 'memora-5db6f.firebasestorage.app',
    measurementId: 'G-PKZ1N2WRHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqCFERGdqeqSf6zGyxCF563KWCaKsjD54',
    appId: '1:84936949380:android:6f4eaaf7d6a397eccc4cd1',
    messagingSenderId: '84936949380',
    projectId: 'memora-5db6f',
    storageBucket: 'memora-5db6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5b_0OWBJvftE9bklzLr6ufAup3pl7Zbw',
    appId: '1:84936949380:ios:8cd8ba5c025d2014cc4cd1',
    messagingSenderId: '84936949380',
    projectId: 'memora-5db6f',
    storageBucket: 'memora-5db6f.firebasestorage.app',
    iosBundleId: 'com.example.memoraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5b_0OWBJvftE9bklzLr6ufAup3pl7Zbw',
    appId: '1:84936949380:ios:8cd8ba5c025d2014cc4cd1',
    messagingSenderId: '84936949380',
    projectId: 'memora-5db6f',
    storageBucket: 'memora-5db6f.firebasestorage.app',
    iosBundleId: 'com.example.memoraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe74ZYUkUYPuWK4YOsAP2NBR-4RaJ7zRo',
    appId: '1:84936949380:web:d4f8b13590b2de82cc4cd1',
    messagingSenderId: '84936949380',
    projectId: 'memora-5db6f',
    authDomain: 'memora-5db6f.firebaseapp.com',
    storageBucket: 'memora-5db6f.firebasestorage.app',
    measurementId: 'G-CJFHSHT1S1',
  );
}
